import React from 'react';
import { Button } from "@/components/ui/button";
import { Plus, Download } from 'lucide-react';
import { format } from 'date-fns';
import { useAuth } from '@/contexts/AuthContext';
import { useBranding } from '@/contexts/BrandingContext';
import { useNavigate } from 'react-router-dom';
import { toast } from 'sonner';

export default function DashboardHeader({ stats, revenueData }) {
    const { user } = useAuth();
    const { company_name } = useBranding();
    const navigate = useNavigate();

    // Get time of day for greeting
    const hour = new Date().getHours();
    let greeting = 'Good Morning';
    if (hour >= 12 && hour < 17) greeting = 'Good Afternoon';
    else if (hour >= 17) greeting = 'Good Evening';

    // Prioritize Company Name if valid, else User Name, else fallback
    const displayName = company_name && company_name !== 'Triponic B2B' ? company_name : (user?.user_metadata?.first_name || 'Travel Pro');

    const handleExport = () => {
        try {
            // Helper to escape CSV fields
            const escapeCsv = (field) => {
                if (field === null || field === undefined) return '';
                const stringField = String(field);
                if (stringField.includes(',') || stringField.includes('"') || stringField.includes('\n')) {
                    return `"${stringField.replace(/"/g, '""')}"`;
                }
                return stringField;
            };

            // Get data from props or fallbacks
            const s = stats || { clients: {}, itineraries: {}, revenue: {}, bookings: {} };
            const rData = (revenueData && revenueData.length > 0) ? revenueData : [];

            // 1. Overview Section
            const overviewRows = [
                ['EXECUTIVE SUMMARY', format(new Date(), 'yyyy-MM-dd')],
                ['Generated By', user?.user_metadata?.first_name || 'System User'],
                [],
                ['METRIC', 'VALUE'],
                ['Total Clients', s.clients?.total || 0],
                ['Active Itineraries', s.itineraries?.total || 0],
                ['Total Bookings', s.bookings?.total || 0],
                ['Pending Bookings', s.bookings?.pending || 0],
                ['YTD Revenue', `$${(s.revenue?.total || 0).toLocaleString()}`],
                []
            ];

            // 2. Monthly Performance Section
            const revenueHeader = [['MONTHLY PERFORMANCE']];
            const revenueCols = [['Month', 'Revenue']];
            // Safe mapping with default 0 check
            const revenueRows = rData.map(m => [m.fullName || 'Unknown', `$${(m.revenue || 0).toLocaleString()}`]);

            // Combine all
            const reportData = [
                ...overviewRows,
                ...revenueHeader,
                ...revenueCols,
                ...revenueRows
            ];

            const csvContent = "data:text/csv;charset=utf-8,"
                + reportData.map(row => row.map(escapeCsv).join(",")).join("\n");

            const encodedUri = encodeURI(csvContent);
            const link = document.createElement("a");
            link.setAttribute("href", encodedUri);
            link.setAttribute("download", `Financial_Report_${format(new Date(), 'yyyy-MM-dd')}.csv`);
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);

            toast.success("Real Data Report exported successfully");
        } catch (e) {
            console.error(e);
            toast.error("Failed to generate report");
        }
    };

    return (
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
            <div>
                <h1 className="text-2xl md:text-3xl font-bold text-slate-900 tracking-tight">
                    {greeting}, {displayName}
                </h1>
                <p className="text-slate-500 mt-1 flex items-center gap-2 text-sm font-medium">
                    {format(new Date(), 'EEEE, MMMM do, yyyy')}
                    <span className="w-1 h-1 rounded-full bg-slate-300"></span>
                    Overview
                </p>
            </div>

            <div className="flex items-center gap-3">
                <Button variant="outline" size="sm" className="hidden sm:flex text-slate-700" onClick={handleExport}>
                    <Download className="w-4 h-4 mr-2" />
                    Export Report
                </Button>

            </div>
        </div>
    );
}
